export const usersActionTypes = {
    // GET ALL
    FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
    // BY ID
    FETCH_USER_BY_ID_REQUEST: 'FETCH_USER_BY_ID_REQUEST',
    FETCH_USER_BY_ID_SUCCESS: 'FETCH_USER_BY_ID_SUCCESS',
    FETCH_USER_BY_ID_FAILURE: 'FETCH_USER_BY_ID_FAILURE',
    // INSERT
    INSERT_REQUEST: 'INSERT_REQUEST',
    INSERT_SUCCESS: 'INSERT_SUCCESS',
    INSERT_FAILURE: 'INSERT_FAILURE',
    // UPDATE
    UPDATE_REQUEST: 'UPDATE_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_FAILURE',
    // DELETE
    DELETE_REQUEST: 'DELETE_REQUEST',
    DELETE_SUCCESS: 'DELETE_SUCCESS',
    DELETE_FAILURE: 'DELETE_FAILURE',
}