export const usersActionTypes = {
    FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
    FETCH_USER_BY_ID_REQUEST: 'FETCH_USER_BY_ID_REQUEST',
    FETCH_USER_BY_ID_SUCCESS: 'FETCH_USER_BY_ID_SUCCESS',
    FETCH_USER_BY_ID_FAILURE: 'FETCH_USER_BY_ID_FAILURE'
}